
name: Python application

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: check git 
      uses: actions/checkout@v3

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.6.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r depend.txt
        
        
    - name: Test with pytest
      run: |
        
        python -m pytest

    